# Generated by Django 6.0 on 2025-12-15 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_created_at_alter_booking_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table_number',
            field=models.IntegerField(choices=[(1, 'Стол 1'), (2, 'Стол 2'), (3, 'Стол 3'), (4, 'Стол 4'), (5, 'Стол 5'), (6, 'Стол 6'), (7, 'Стол 7'), (8, 'Стол 8'), (9, 'Стол 9'), (10, 'Стол 10')], default=1, verbose_name='Номер столика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30')], max_length=5, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
